<header>
	<span id = "openSideNav" style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
	<svg height="130" width="200" id = "logo">
			<defs>
			    <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
			      <stop offset="0%" style="stop-color:#379683;stop-opacity:1" />
			      <stop offset="100%" style="stop-color:#EDF5E1;stop-opacity:1" />
		    	</linearGradient>
            </defs>
	    <ellipse cx="100" cy="70" rx="85" ry="55" fill="url(#grad1)" />
	    <text fill="#ffffff" font-size="45" font-family="Verdana" x="50" y="86">SITC</text>
	</svg>	
	<h1>Super IT Consultant</h1>
</header>